### PR TITLE
Add new quote from Doug

### PR DESCRIPTION
**Pull request by mestery**
Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by dougwig** [comment]
Not generic enough to answer any question.  -1.  👎 
:)

**Comment by johnotander** [comment]
Perhaps it could be amended to "Fuck a duck", @dougwig?

**Comment by Cedev** [comment]
+2

**Comment by johno** [comment]
Manually added since there are now merge conflicts. Thx!

**Pull request closed without merging**
